apiVersion: v1
kind: Service
metadata:
    name: "aksazsingaporemeetupdemo-5465"
    labels:
        app: "aksazsingaporemeetupdemo-5465"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aksazsingaporemeetupdemo-5465"