on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.acrazsingaporemeetupdemo_5465 }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n acrazsingaporemeetupdemo -g acrazsingaporemeetupdemo9322-rg --location "South India" --sku Basic --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n acrazsingaporemeetupdemo --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n acrazsingaporemeetupdemo --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n acrazsingaporemeetupdemo --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: acrazsingaporemeetupdemo.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/." -f  "Dockerfile" -t acrazsingaporemeetupdemo.azurecr.io/aksazsingaporemeetupdemo5465:${{ github.sha }}
        docker push acrazsingaporemeetupdemo.azurecr.io/aksazsingaporemeetupdemo5465:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_aksazsingaporemeetupdemo_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aksazsingaporemeetupdemo5465 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aksazsingaporemeetupdemo5465`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aksazsingaporemeetupdemo5465
        container-registry-url: acrazsingaporemeetupdemo.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: aksazsingapodockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aksazsingaporemeetupdemo5465
        manifests: |
          ./manifests/deployment-5465.yml
          ./manifests/service-5465.yml
        images: |
          acrazsingaporemeetupdemo.azurecr.io/aksazsingaporemeetupdemo5465:${{ github.sha }}
        imagepullsecrets: |
          aksazsingapodockerauth